pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    ls -la
    curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $(cat rust-toolchain)
    echo "##vso[task.prependpath]$HOME/.cargo/bin"
  displayName: 'Install Rust'

- script: |
    sudo apt-get update
    sudo apt-get install -y libmariadb-dev
  displayName: Install libmysql

- script: |
    rustc -Vv
    cargo -V
  displayName: Query rust and cargo versions

- script : cargo build --features sqlite enable_syslog
  displayName: 'Build project with sqlite backend'

- script : cargo build --features mysql enable_syslog
  displayName: 'Build project with mysql backend'
