blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions for Vaultwarden
    url: https://github.com/vaultwarden/vaultwarden/discussions
    about: Use the discussions to request features or get help with usage/configuration.
  - name: Discourse forum for Vaultwarden
    url: https://vaultwarden.discourse.group/
    about: An alternative to the GitHub Discussions, if this is easier for you.
