name: Cleanup
permissions: {}

on:
  workflow_dispatch:
    inputs:
      manual_trigger:
        description: "Manual trigger cleanup"
        required: false
        default: ""

  schedule:
    - cron: '0 1 * * FRI'

jobs:
  cleanup:
    name: Cleanup
    permissions:
      packages: write # To be able to cleanup old caches
    runs-on: ubuntu-24.04
    continue-on-error: true
    timeout-minutes: 30
    strategy:
      matrix:
        package: ["vaultwarden-buildache", "vaultwarden-dryrun"]
    steps:
      - name: Delete ${{ matrix.package }} containers
        uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # v5.0.0
        with:
          package-name: '${{ matrix.package }}'
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'false'
