on:
  workflow_dispatch:
    inputs:
      manual_trigger:
        description: "Manual trigger buildcache cleanup"
        required: false
        default: ""

  schedule:
    - cron: '0 1 * * FRI'

name: Cleanup
jobs:
  releasecache-cleanup:
    name: Releasecache Cleanup
    runs-on: ubuntu-24.04
    continue-on-error: true
    timeout-minutes: 30
    steps:
      - name: Delete vaultwarden-buildcache containers
        uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # v5.0.0
        with:
          package-name: 'vaultwarden-buildcache'
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'false'
